<?xml version="1.0"?>
<!DOCTYPE resourcesTree [
	<!ELEMENT resourcesTree (type)+>
	<!ELEMENT type (type|resource)*>
	<!ELEMENT resource (#PCDATA)>
	<!ATTLIST type
      name         CDATA    #REQUIRED
      icon         CDATA    #IMPLIED
      collapsed    CDATA    #IMPLIED
      experimental (yes|no) "no"
    >
	<!ATTLIST resourcesTree
    	version CDATA #REQUIRED
    >
	<!ATTLIST resource
    	name CDATA #REQUIRED
        icon CDATA #IMPLIED
    >
]>
<resourcesTree version="3">
	
	<type name="Calculation components" collapsed="0">
		<type name="Capacity analysis" collapsed="0">
			<resource name="kappalab___capacityEntropy___1.0"/>
			<resource name="kappalab___capacityFavor___1.0"/>
			<resource name="kappalab___capacityInteraction___1.0"/>
			<resource name="kappalab___capacityOrness___1.0"/>
			<resource name="kappalab___capacityShapley___1.0"/>
			<resource name="kappalab___capacityVariance___1.0"/>
			<resource name="kappalab___capacityVeto___1.0"/>
		</type>
		
		<type name="Capacity identification" collapsed="0">
			<resource name="kappalab___leastSquaresCapaIdent___1.0"/>
			<resource name="kappalab___linProgCapaIdent___1.0"/>
			<resource name="kappalab___lsRankingCapaIdent___1.0"/>
			<resource name="kappalab___miniVarCapaIdent___1.0"/>
		</type>
		
		<type name="Aggregation" collapsed="0">
			<resource name="kappalab___choquetIntegral___1.0"/>
			<type name="Weighted Sum" collapsed="0">
				<resource name="PyXMCDA___weightedSum___1.0"/>
				<resource name="UTAR___generalWeightedSum___1.0"/>
			</type>
		</type>
		
		<type name="Outranking" collapsed="0">
			<resource name="PyXMCDA___RubisConcordanceRelation___1.0"/>
			<resource name="J-MCDA___concordance___0.0.4"/>
			<resource name="J-MCDA___discordances___0.0.4"/>
			<resource name="J-MCDA___outranking___0.0.4"/>
			<resource name="J-MCDA___cutRelation___0.0.4"/>
			<resource name="J-MCDA___preference___0.0.4"/>
			<resource name="J-MCDA___flows___0.0.4"/>
		</type>
		
		<type name="Disaggregation" collapsed="0">
		    <resource name="PyXMCDA___weightsFromCondorcetRelation___1.0"/>
		    <resource name="PyXMCDA___weightsFromCondorcetAndPreferences___1.0"/>
		    <resource name="UTAR___ACUTA___1.0"/>
		</type>
		
		<type name="Alternatives analysis" collapsed="0">
			<resource name="RXMCDA___alternativesValuesKendall___1.0"/>
			<resource name="RXMCDA___rankAlternativesValues___1.0"/>
		</type>
		<type name="Alternatives computations" collapsed="0">
			<resource name="UTAR___computeNormalisedPerformanceTable___1.0"/>
		</type>
	</type>

	<type name="Methods" collapsed="0">
		<resource name="jsmaa___smaa2___0.2"/>
	</type>

	<type name="Visualisation components" collapsed="0">
		<resource name="RXMCDA___plotAlternativesComparisons___1.0"/>
		<resource name="RXMCDA___plotAlternativesValues___1.0"/>
		<resource name="RXMCDA___plotAlternativesValuesPreorder___1.0"/>
		<resource name="RXMCDA___plotCriteriaComparisons___1.0"/>
		<resource name="RXMCDA___plotCriteriaValues___1.0"/>
		<resource name="RXMCDA___plotCriteriaValuesPreorder___1.0"/>
		<resource name="RXMCDA___plotNumericPerformanceTable___1.0"/>
		<resource name="UTAR___XYPlotAlternativesValues___1.0"/>
		<resource name="UTAR___plotValueFunctions___1.0"/>
	</type>

		<type name="Reporting" collapsed="0">
		    <resource name="RXMCDA___generateXMCDAReport___1.0"/>
		</type>
		
	<!-- <type name="Development" collapsed="1">
		<resource name="DecisionDeck___kappalabServer___1.0"/>
		<resource name="DecisionDeck___kappalab___1.0"/>
		<resource name="DecisionDeck___splitXMCDA___1.0"/>
		<resource name="DecisionDeck___normalize___1.0"/>
		<resource name="DecisionDeck___kappalab_O2I___1.0"/>
		<resource name="DecisionDeck___kappalabComponent___1.0"/>
		<resource name="DecisionDeck___assembleXMCDA___1.0"/>
	</type> -->

</resourcesTree>
